### ISSUE TITLE
createGlobalStyles error: TypeError: fn is not a function

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-styled-components#19]
```ts
createGlobalStyles`
span.red {
  color: red;
}
`
```

```
TypeError: fn is not a function
    at GlobalStyles (/@fs/work/solid-styled-components/src/index.js:82:5)
    at Proxy.createComponent (/work/solid-styled-components/node_modules/.pnpm/solid-js@1.3.7/node_modules/solid-js/dist/server.cjs:247:15)
    at /work/solid-styled-components/apps/esg-solid-web/src/routes/companies/:company_locator/index.tsx:157:30
    at Proxy.createComponent (/work/solid-styled-components/node_modules/.pnpm/solid-js@1.3.7/node_modules/solid-js/dist/server.cjs:247:15)
    at Object.get children [as children] (/work/solid-styled-components/libs/solid/src/Singleton_.tsx:12:5)
    at Singleton (/work/solid-styled-components/libs/solid/src/Singleton.tsx:7:1)
    at Proxy.createComponent (/work/solid-styled-components/node_modules/.pnpm/solid-js@1.3.7/node_modules/solid-js/dist/server.cjs:247:15)
    at /work/solid-styled-components/libs/solid/src/Singleton_.tsx:11:4
    at Proxy.createComponent (/work/solid-styled-components/node_modules/.pnpm/solid-js@1.3.7/node_modules/solid-js/dist/server.cjs:247:15)
    at Company (/work/solid-styled-components/apps/esg-solid-web/src/routes/companies/:company_locator/index.tsx:73:3)
```

Introduced in https://github.com/solidjs/solid-styled-components/pull/13
